make decodeFont and decodeAudio non virtual
This was causing the Lambda recorder builds to fail as these methods weren't linking properly because they were never overridden (super strange seems like a compiler or linker bug). We don't need these to be virtual as the logic for returning the correct concrete object is always known at compile time.

```
Linking rive_thumbnail_generator
/usr/bin/ld:../../renderer/build/linux/bin/release/librive_skia_renderer.a(skia_factory.o):(.data.rel.ro+0x190): undefined reference to `rive::Factory::decodeFont(rive::Span<unsigned char const>)'
/usr/bin/ld:../../renderer/build/linux/bin/release/librive_skia_renderer.a(skia_factory.o):(.data.rel.ro+0x198): undefined reference to `rive::Factory::decodeAudio(rive::Span<unsigned char const>)'
clang: error:linker command failed with exit code 1 (use -v to see invocation)
```

Diffs=
aee913977a make decodeFont and decodeAudio non virtual (#9025)

Co-authored-by: Luigi Rosso <luigi-rosso@users.noreply.github.com>