Fix tess viewer compile
Disable TextContent Viewers in non-Skia renderers as the Harfbuzz RenderFont is provided by the SkiaRenderer (we should consider moving this to Rive directly or some RiveBaseRenderer library).

I was getting errors like this:
```
textpath_content.cpp
../src/viewer_content/text_content.cpp:20:10: fatal error: 'renderfont_hb.hpp' file not found
#include "renderfont_hb.hpp"
         ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

I could've just had the Viewer always depend on the SkiaRenderer, but I think it's better to consider where we really want the HB RenderFont to live...

Diffs=
8dd7e91cd fix viewer build