Update version to macosx 11 for runtime.
Sorry for the churn in the premake file, someone didn't use the right formatter in a previous commit.

We had to bump to 11 for this:
```
../../../../../../pls/renderer/metal/background_shader_compiler.mm:215:42: error: 'MTLLanguageVersion2_3' is only available on macOS 11.0 or newer [-Werror,-Wunguarded-availability-new]
        compileOptions.languageVersion = MTLLanguageVersion2_3; // On mac, we need version 2.3+
                                         ^~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.2.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLLibrary.h:190:5: note: 'MTLLanguageVersion2_3' has been marked as being introduced in macOS 11.0 here, but the deployment target is macOS 10.6.0
    MTLLanguageVersion2_3 API_AVAILABLE(macos(11.0), ios(14.0)) = (2 << 16) + 3,
    ^
../../../../../../pls/renderer/metal/background_shader_compiler.mm:215:42: note: enclose 'MTLLanguageVersion2_3' in an @available check to silence this warning
        compileOptions.languageVersion = MTLLanguageVersion2_3; // On mac, we need version 2.3+
                                         ^~~~~~~~~~~~~~~~~~~~~
../../../../../../pls/renderer/metal/background_shader_compiler.mm:220:28: error: 'setPreserveInvariance:' is only available on macOS 11.0 or newer [-Werror,-Wunguarded-availability-new]
            compileOptions.preserveInvariance = YES;
```

Diffs=
e75b8fa63 Update version to macosx 11 for runtime. (#7829)

Co-authored-by: Luigi Rosso <luigi-rosso@users.noreply.github.com>